name: CI

on:
  push:
    branches-ignore:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Build site
        run: bundle exec jekyll build

      - name: Check HTML
        run: |
          bundle exec htmlproofer ./_site \
            --disable-external \
            --ignore-urls "/localhost/" \
            --allow-hash-href
        continue-on-error: true
